"""Disposition models for triage outcomes."""

from datetime import datetime
from enum import Enum

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin


class RiskFlagType(str, Enum):
    """Types of risk flags."""

    SUICIDE_RISK = "SUICIDE_RISK"
    VIOLENCE_RISK = "VIOLENCE_RISK"
    PSYCHOSIS_RISK = "PSYCHOSIS_RISK"
    MANIA_RISK = "MANIA_RISK"
    SUBSTANCE_RISK = "SUBSTANCE_RISK"
    MEDICATION_RISK = "MEDICATION_RISK"
    SAFEGUARDING = "SAFEGUARDING"
    SEVERITY = "SEVERITY"
    COMPLEXITY = "COMPLEXITY"
    PRESENTATION = "PRESENTATION"


class RiskSeverity(str, Enum):
    """Risk severity levels."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskFlag(Base, TimestampMixin):
    """Risk flag identified during triage evaluation.

    Flags are generated by the rules engine and stored for
    clinical review and audit purposes.
    """

    __tablename__ = "risk_flags"

    triage_case_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("triage_cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Rule that generated this flag
    rule_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    # Type of risk flag
    flag_type: Mapped[RiskFlagType] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )
    # Severity level
    severity: Mapped[RiskSeverity] = mapped_column(
        String(20),
        nullable=False,
    )
    # Human-readable explanation
    explanation: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )
    # Whether this flag has been reviewed by a clinician
    reviewed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
    )
    # ID of clinician who reviewed (if applicable)
    reviewed_by: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    # Review notes
    review_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    def __repr__(self) -> str:
        return f"<RiskFlag {self.flag_type.value} severity={self.severity.value}>"


class DispositionDraft(Base, TimestampMixin):
    """Draft disposition generated by rules engine.

    Stores the proposed triage outcome before clinical approval.
    Multiple drafts may exist if re-evaluated.
    """

    __tablename__ = "disposition_drafts"

    triage_case_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("triage_cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Assigned tier (RED, AMBER, GREEN, BLUE)
    tier: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
    )
    # Recommended pathway
    pathway: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    # Whether self-booking is allowed
    self_book_allowed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
    )
    # Whether clinician review is required
    clinician_review_required: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
    )
    # List of rule IDs that fired
    rules_fired: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )
    # Explanations from fired rules
    explanations: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )
    # Ruleset version used
    ruleset_version: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    # Ruleset content hash
    ruleset_hash: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
    )
    # Full evaluation context (for debugging/audit)
    evaluation_context: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
    )
    # Whether this draft has been approved/applied
    is_applied: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
    )
    # Who approved this draft
    approved_by: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    def __repr__(self) -> str:
        status = "applied" if self.is_applied else "draft"
        return f"<DispositionDraft tier={self.tier} pathway={self.pathway} ({status})>"


class DispositionFinal(Base, TimestampMixin):
    """Final disposition after clinician review.

    Stores the confirmed or overridden disposition.
    If overridden, rationale is required for audit compliance.
    """

    __tablename__ = "disposition_finals"

    triage_case_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("triage_cases.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,  # One final disposition per case
        index=True,
    )
    # Reference to the draft that was confirmed (if applicable)
    draft_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("disposition_drafts.id", ondelete="SET NULL"),
        nullable=True,
    )
    # Final tier (may differ from draft if overridden)
    tier: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
    )
    # Final pathway (may differ from draft if overridden)
    pathway: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    # Whether self-booking is allowed
    self_book_allowed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
    )
    # Whether this was an override of the original draft
    is_override: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
    )
    # Original tier from draft (for audit when overridden)
    original_tier: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
    )
    # Original pathway from draft (for audit when overridden)
    original_pathway: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )
    # Rationale for decision (REQUIRED if is_override=True)
    rationale: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )
    # Clinician who finalized the disposition
    clinician_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    # When the disposition was finalized
    finalized_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )
    # Additional notes for clinical record
    clinical_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    def __repr__(self) -> str:
        override_str = " (overridden)" if self.is_override else ""
        return f"<DispositionFinal tier={self.tier} pathway={self.pathway}{override_str}>"
